spring:
  application:
    name: stc-strava

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_demo
    username: root
    password: admin23456

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

security:
  oauth2:
    client:
      client-id: 63592
      client-secret: 2f429b0d8b1fb765a86a147c985d229d9697800d

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#http://localhost:8080/oauth2/authorization/strava