server:
  port: 9292

spring:
  application:
    name: stc-strava

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quyen1?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

security:
  oauth2:
    client:
      client-id: 63587
      client-secret: 90d9886e663cc8ab2cc408cfae62ae72cacb5586

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#http://localhost:8080/oauth2/authorization/strava