spring:
  application:
    name: stc-strava

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_demo
    username: root
    password: admin23456

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  security:
    oauth2:
      client:
        registration:
          strava:
            provider: strava-provider
            client-id: ${CLIENT-ID:63592}
            client-secret: ${CLIENT-SECRET:2f429b0d8b1fb765a86a147c985d229d9697800d}
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: http://192.168.88.160:8080/login/oauth2/code/strava
            scope: activity:read_all
        provider:
          strava-provider:
            tokenUri: https://www.strava.com/oauth/token
            user-info-uri: https://www.strava.com/api/v3/athlete
            user-name-attribute: id
            authorization-uri: https://www.strava.com/oauth/authorize
            token-uri: https://www.strava.com/oauth/token

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#http://localhost:8080/oauth2/authorization/strava